# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x05proto\"A\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"/\n\x0c\x41uthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"D\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2{\n\x07Greeter\x12\x37\n\x0c\x41uthenticate\x12\x12.proto.UserRequest\x1a\x13.proto.AuthResponse\x12\x37\n\x08Register\x12\x12.proto.UserRequest\x1a\x17.proto.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=24
  _globals['_USERREQUEST']._serialized_end=89
  _globals['_AUTHRESPONSE']._serialized_start=91
  _globals['_AUTHRESPONSE']._serialized_end=138
  _globals['_REGISTERRESPONSE']._serialized_start=140
  _globals['_REGISTERRESPONSE']._serialized_end=208
  _globals['_GREETER']._serialized_start=210
  _globals['_GREETER']._serialized_end=333
# @@protoc_insertion_point(module_scope)
