# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x07greeter\"\x07\n\x05\x45mpty\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\rIndexResponse\x12\x14\n\x0chtml_content\x18\x01 \x01(\t\"1\n\x0bSyncRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1f\n\x0cSyncResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\x19\x43heckUserExistenceRequest\x12\x10\n\x08username\x18\x01 \x01(\t\",\n\x1a\x43heckUserExistenceResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"\x0e\n\x0c\x45mptyRequest\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t2\xd7\x02\n\x07Greeter\x12\x36\n\x0cGetIndexPage\x12\x0e.greeter.Empty\x1a\x16.greeter.IndexResponse\x12;\n\x0c\x41uthenticate\x12\x14.greeter.AuthRequest\x1a\x15.greeter.AuthResponse\x12;\n\x0cSyncUserData\x12\x14.greeter.SyncRequest\x1a\x15.greeter.SyncResponse\x12;\n\x08Register\x12\x18.greeter.RegisterRequest\x1a\x15.greeter.AuthResponse\x12]\n\x12\x43heckUserExistence\x12\".greeter.CheckUserExistenceRequest\x1a#.greeter.CheckUserExistenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_AUTHREQUEST']._serialized_start=35
  _globals['_AUTHREQUEST']._serialized_end=84
  _globals['_AUTHRESPONSE']._serialized_start=86
  _globals['_AUTHRESPONSE']._serialized_end=134
  _globals['_INDEXRESPONSE']._serialized_start=136
  _globals['_INDEXRESPONSE']._serialized_end=173
  _globals['_SYNCREQUEST']._serialized_start=175
  _globals['_SYNCREQUEST']._serialized_end=224
  _globals['_SYNCRESPONSE']._serialized_start=226
  _globals['_SYNCRESPONSE']._serialized_end=257
  _globals['_CHECKUSEREXISTENCEREQUEST']._serialized_start=259
  _globals['_CHECKUSEREXISTENCEREQUEST']._serialized_end=304
  _globals['_CHECKUSEREXISTENCERESPONSE']._serialized_start=306
  _globals['_CHECKUSEREXISTENCERESPONSE']._serialized_end=350
  _globals['_EMPTYREQUEST']._serialized_start=352
  _globals['_EMPTYREQUEST']._serialized_end=366
  _globals['_REGISTERREQUEST']._serialized_start=368
  _globals['_REGISTERREQUEST']._serialized_end=421
  _globals['_GREETER']._serialized_start=424
  _globals['_GREETER']._serialized_end=767
# @@protoc_insertion_point(module_scope)
