# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x07greeter\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1f\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"1\n\x0bSyncRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1f\n\x0cSyncResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x83\x01\n\x07Greeter\x12;\n\x0c\x41uthenticate\x12\x14.greeter.AuthRequest\x1a\x15.greeter.AuthResponse\x12;\n\x0cSyncUserData\x12\x14.greeter.SyncRequest\x1a\x15.greeter.SyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=26
  _globals['_AUTHREQUEST']._serialized_end=75
  _globals['_AUTHRESPONSE']._serialized_start=77
  _globals['_AUTHRESPONSE']._serialized_end=108
  _globals['_SYNCREQUEST']._serialized_start=110
  _globals['_SYNCREQUEST']._serialized_end=159
  _globals['_SYNCRESPONSE']._serialized_start=161
  _globals['_SYNCRESPONSE']._serialized_end=192
  _globals['_GREETER']._serialized_start=195
  _globals['_GREETER']._serialized_end=326
# @@protoc_insertion_point(module_scope)
